"""empty message

Revision ID: b56716baa066
Revises: None
Create Date: 2016-04-08 01:15:57.213168

"""

# revision identifiers, used by Alembic.
revision = 'b56716baa066'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['rec_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column(u'rec_events', 'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'rec_events', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('volunteers')
    ### end Alembic commands ###
